# SERVER CONFIGURATION
server:
  port: 8085

# APP CONFIGURATION
spring:
  application:
    name: http-handler-2

# FEIGN CLIENT
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic