# SERVER CONFIGURATION
server:
  port: 8083

# APP CONFIGURATION
spring:
  application:
    name: orchestrator
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-orchestrator