# SERVER CONFIGURATION
server:
  port: 8081

# APP CONFIGURATION
spring:
  application:
    name: coordinator
  datasource:
    url: jdbc:postgresql://localhost:5432/registrator
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: registrator
  kafka:
    bootstrap-servers: localhost:29092